parameters:
#    e_learning_main.example.class: ELearning\MainBundle\Example

services:
#    e_learning_main.example:
#        class: %e_learning_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
